language: objective-c
osx_image: xcode8.2
env:
global:
- LC_CTYPE=en_US.UTF-8
- LANG=en_US.UTF-8
- PROJECT=CRDCrypt.xcodeproj
- IOS_SCHEME="CRDCryptMobile"
- IOS_SCHEME_TEST="CRDCryptMobileTests"
- IOS_SDK=iphonesimulator10.2
- OSX_SCHEME="CRDCryptMac"
- OSX_SCHEME_TEST="CRDCryptMacTests"
- OSX_SDK=macosx10.12
matrix:
- DESTINATION="id=7B6F8C6B-B67A-4F64-BB70-AE1FF077ACC2" SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" RUN_TESTS="NO" POD_LINT="NO"
- DESTINATION="id=7B6F8C6B-B67A-4F64-BB70-AE1FF077ACC2" SCHEME="$IOS_SCHEME_TEST" SDK="$IOS_SDK" RUN_TESTS="YES" POD_LINT="NO"
- DESTINATION="arch=x86_64" SCHEME="$OSX_SCHEME" SDK="$OSX_SDK" RUN_TESTS="NO" POD_LINT="NO"
- DESTINATION="arch=x86_64" SCHEME="$OSX_SCHEME_TEST" SDK="$OSX_SDK" RUN_TESTS="YES" POD_LINT="NO"

script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks

# Build Framework in Debug and Run Tests if specified
- if [ "$RUN_TESTS" == "YES" ]; then xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test; else xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build; fi

# Run pod lib lint if specified
- if [ "$POD_LINT" == "YES" ]; then pod lib lint --private --verbose; fi
